
server.port: 8084
app.name: myconfigproject
greating.message: Hello from yml to ${app.name}
my:
 list: abc, xyz, uvw
 dbvalues.as.object: "{connectionUrl: 'http://url', username:'foo', password:'pass'}"

db:
 connection: http://url
 host: dbhost
 port: 8525

management.endpoints.web.exposure.include: "*"
#http://localhost:8080/actuator/configprops

#spring: profiles:active: test

spring:
 config:
   import: optional:configserver:http://localhost:8888
 application:
   name: io.ms.config.client

#cloud:config:uri: http://localhost:8888

